### ISSUE TITLE
Thank You and Questions

### ISSUE THREAD

**Issue by janetmango** [Lamikins/FitBitica#1]
First of all, thank you so much for making this app to link FitBit with Habitica!!  I have wanted this communication link since I joined last year. 

I'm trying the app and it's reading my step count from FitBit and it's seeing my Habitica info, so that is all working well.

For metrics to track, do they have to be Habits?  Or can they be Dailies?  Just trying to understand a little more.

Also, can we track multiple levels of steps?  For example, I had a Daily for 5000 steps, another Daily for 7500 steps, another Daily for 10000 steps. Then I could check each one as  I completed it.  Does the app work similarly?  Or does it only track one step count value?

Can we also add Floors Climbed? That's another value I track.

Do we need to leave the FitBitica page open so the script will run?

What exactly happens when we reach our metric? Do we get a notification in the game that a task has been completed (just like clicking a + Habit?)

Sorry for all the questions, but I'm really excited about this!!

**Comment by janetmango** [comment]
I had one other thought:  can we get Calories Eaten as well?

**Comment by Lamikins** [comment]
Hi!

Thank you so much for taking interest!

For your questions:
- At this time, FitBitica can only track habits because they're really easy
to score multiple times.  It would be great to add that feature someday,
though.

- The levels of steps functionality is basically built-in.  For your
example, 5000:7500:10000, FitBitica could do the same thing if you put a
habit called "2500 steps taken"  and every time you walk 2500 steps it
upvotes your habit again.  So it upvotes your habit every multiple of 2500
steps.

That's how it works for all of the metrics, so by putting 1 miles traveled
(currently hard coded so grammar is off :) the app upvotes your "1 miles
traveled" habit every mile you walk.

- Floors climbed is not currently implemented, but it is also a good idea!
Something to go on the to-do list.

- The page should stay open to run.  I just keep it minimized because it
works automatically.

- When you reach your metric in real life (like after a running workout)
you may have to wait for a bit for your device to sync with fitbit's
servers first.  Once it does, the app will automatically refresh itself
(every 3 mins) and get your updated data.  You can also press the refresh
data button to do it manually.

This upvotes your habits in the background and updates your habitica stats
on the page, but not much else happens.  When you refresh/sync your
habitica page, however, it should reflect the new additions!

Do you think there should be a better notification system?  I'm totally
open to any and all suggestions!

Also, are you a coder?  If you'd like to make additions to FitBitica,
please go ahead and fork the repo!

Thanks!
-Darius

**Comment by janetmango** [comment]
Thanks so much for the clarified instructions!! It might be a good idea to add a modified version of your instructions on the wiki page and the FitBitica page because they're very helpful.

With this additional information, I made some changes to my Habits and they're working beautifully!!  All the 3 that  I added have already been upticked, turned green, and I got notifications about XP, etc. when I sync'ed the page.

Unfortunately, I'm not a programmer so I can't help, but I like helping to debug and give feedback, so I'll be glad to do that.
